export type Severity = "mild" | "moderate" | "severe";

export interface OffensiveEntry {
  word: string;
  romanized: string;
  language: string;
  languageCode: string;
  severity: Severity;
}

export const OFFENSIVE_DICTIONARY: OffensiveEntry[] = [
  // Hindi — Devanagari + Romanized
  {
    word: "बेवकूफ",
    romanized: "bevakoof",
    language: "Hindi",
    languageCode: "hi-IN",
    severity: "mild",
  },
  {
    word: "गधा",
    romanized: "gadha",
    language: "Hindi",
    languageCode: "hi-IN",
    severity: "mild",
  },
  {
    word: "कमीना",
    romanized: "kameena",
    language: "Hindi",
    languageCode: "hi-IN",
    severity: "moderate",
  },
  {
    word: "हरामी",
    romanized: "harami",
    language: "Hindi",
    languageCode: "hi-IN",
    severity: "moderate",
  },
  {
    word: "साला",
    romanized: "saala",
    language: "Hindi",
    languageCode: "hi-IN",
    severity: "moderate",
  },
  {
    word: "कुत्ता",
    romanized: "kutta",
    language: "Hindi",
    languageCode: "hi-IN",
    severity: "moderate",
  },
  {
    word: "चुटिया",
    romanized: "chutiya",
    language: "Hindi",
    languageCode: "hi-IN",
    severity: "severe",
  },
  {
    word: "मादरचोद",
    romanized: "madarchod",
    language: "Hindi",
    languageCode: "hi-IN",
    severity: "severe",
  },
  {
    word: "भड़वा",
    romanized: "bhadwa",
    language: "Hindi",
    languageCode: "hi-IN",
    severity: "severe",
  },
  {
    word: "रांडी",
    romanized: "randi",
    language: "Hindi",
    languageCode: "hi-IN",
    severity: "severe",
  },
  {
    word: "बहनचोद",
    romanized: "behenchod",
    language: "Hindi",
    languageCode: "hi-IN",
    severity: "severe",
  },
  {
    word: "गांडू",
    romanized: "gaandu",
    language: "Hindi",
    languageCode: "hi-IN",
    severity: "severe",
  },
  {
    word: "चूतिया",
    romanized: "chutiya",
    language: "Hindi",
    languageCode: "hi-IN",
    severity: "severe",
  },
  {
    word: "लंड",
    romanized: "lund",
    language: "Hindi",
    languageCode: "hi-IN",
    severity: "severe",
  },
  {
    word: "लंडू",
    romanized: "landu",
    language: "Hindi",
    languageCode: "hi-IN",
    severity: "severe",
  },
  {
    word: "गांड",
    romanized: "gaand",
    language: "Hindi",
    languageCode: "hi-IN",
    severity: "severe",
  },
  {
    word: "गांडू",
    romanized: "gaandoo",
    language: "Hindi",
    languageCode: "hi-IN",
    severity: "severe",
  },
  {
    word: "चूत",
    romanized: "chut",
    language: "Hindi",
    languageCode: "hi-IN",
    severity: "severe",
  },
  {
    word: "चूतड़",
    romanized: "chutad",
    language: "Hindi",
    languageCode: "hi-IN",
    severity: "severe",
  },
  {
    word: "चूतिया",
    romanized: "chutiya",
    language: "Hindi",
    languageCode: "hi-IN",
    severity: "severe",
  },

  // Gujarati
  {
    word: "ગધેડો",
    romanized: "gadhedo",
    language: "Gujarati",
    languageCode: "gu-IN",
    severity: "mild",
  },
  {
    word: "ડફોળ",
    romanized: "dafol",
    language: "Gujarati",
    languageCode: "gu-IN",
    severity: "mild",
  },
  {
    word: "બેવકૂફ",
    romanized: "bevakoof",
    language: "Gujarati",
    languageCode: "gu-IN",
    severity: "mild",
  },
  {
    word: "ઘેલો",
    romanized: "ghelo",
    language: "Gujarati",
    languageCode: "gu-IN",
    severity: "mild",
  },
  {
    word: "હરામી",
    romanized: "harami",
    language: "Gujarati",
    languageCode: "gu-IN",
    severity: "moderate",
  },
  {
    word: "કમીનો",
    romanized: "kameeno",
    language: "Gujarati",
    languageCode: "gu-IN",
    severity: "moderate",
  },
  {
    word: "ચૂતિયો",
    romanized: "chutiyo",
    language: "Gujarati",
    languageCode: "gu-IN",
    severity: "severe",
  },
  {
    word: "ભડવો",
    romanized: "bhadvo",
    language: "Gujarati",
    languageCode: "gu-IN",
    severity: "severe",
  },
  {
    word: "રાંડ",
    romanized: "raand",
    language: "Gujarati",
    languageCode: "gu-IN",
    severity: "severe",
  },
  {
    word: "માદરચોદ",
    romanized: "madarchod",
    language: "Gujarati",
    languageCode: "gu-IN",
    severity: "severe",
  },
  {
    word: "ગાંડો",
    romanized: "gando",
    language: "Gujarati",
    languageCode: "gu-IN",
    severity: "severe",
  },
  {
    word: "ચૂત",
    romanized: "chut",
    language: "Gujarati",
    languageCode: "gu-IN",
    severity: "severe",
  },
  {
    word: "ચૂતડી",
    romanized: "chutdi",
    language: "Gujarati",
    languageCode: "gu-IN",
    severity: "severe",
  },
  {
    word: "ચૂતિયા",
    romanized: "chutiya",
    language: "Gujarati",
    languageCode: "gu-IN",
    severity: "severe",
  },
  {
    word: "ગાંડો",
    romanized: "gando",
    language: "Gujarati",
    languageCode: "gu-IN",
    severity: "severe",
  },
  {
    word: "ગાંડ",
    romanized: "gaand",
    language: "Gujarati",
    languageCode: "gu-IN",
    severity: "severe",
  },
  {
    word: "ગાંડુ",
    romanized: "gaandu",
    language: "Gujarati",
    languageCode: "gu-IN",
    severity: "severe",
  },
  {
    word: "ચૂત",
    romanized: "chut",
    language: "Gujarati",
    languageCode: "gu-IN",
    severity: "severe",
  },
  {
    word: "ચૂતડી",
    romanized: "chutdi",
    language: "Gujarati",
    languageCode: "gu-IN",
    severity: "severe",
  },
  {
    word: "ચૂતિયા",
    romanized: "chutiya",
    language: "Gujarati",
    languageCode: "gu-IN",
    severity: "severe",
  },
  {
    word: "ગાંડો",
    romanized: "gando",
    language: "Gujarati",
    languageCode: "gu-IN",
    severity: "severe",
  },
  {
    word: "ગાંડ",
    romanized: "gaand",
    language: "Gujarati",
    languageCode: "gu-IN",
    severity: "severe",
  },
  {
    word: "ગાંડુ",
    romanized: "gaandu",
    language: "Gujarati",
    languageCode: "gu-IN",
    severity: "severe",
  },

  // Tamil
  {
    word: "முட்டாள்",
    romanized: "muttaal",
    language: "Tamil",
    languageCode: "ta-IN",
    severity: "mild",
  },
  {
    word: "கழுதை",
    romanized: "kazhuthai",
    language: "Tamil",
    languageCode: "ta-IN",
    severity: "mild",
  },
  {
    word: "பொட்டை",
    romanized: "pottai",
    language: "Tamil",
    languageCode: "ta-IN",
    severity: "moderate",
  },
  {
    word: "தேவடியா",
    romanized: "thevidiya",
    language: "Tamil",
    languageCode: "ta-IN",
    severity: "severe",
  },
  {
    word: "ஓத்தா",
    romanized: "otha",
    language: "Tamil",
    languageCode: "ta-IN",
    severity: "severe",
  },
  {
    word: "சுன்னி",
    romanized: "sunni",
    language: "Tamil",
    languageCode: "ta-IN",
    severity: "severe",
  },
  {
    word: "புண்டை",
    romanized: "pundai",
    language: "Tamil",
    languageCode: "ta-IN",
    severity: "severe",
  },
  {
    word: "மயிரு",
    romanized: "mayiru",
    language: "Tamil",
    languageCode: "ta-IN",
    severity: "moderate",
  },

  // Telugu
  {
    word: "దున్నపోతు",
    romanized: "dunnapothu",
    language: "Telugu",
    languageCode: "te-IN",
    severity: "mild",
  },
  {
    word: "వెధవ",
    romanized: "vedhava",
    language: "Telugu",
    languageCode: "te-IN",
    severity: "moderate",
  },
  {
    word: "లంజ",
    romanized: "lanja",
    language: "Telugu",
    languageCode: "te-IN",
    severity: "severe",
  },
  {
    word: "దెంగు",
    romanized: "dengu",
    language: "Telugu",
    languageCode: "te-IN",
    severity: "severe",
  },
  {
    word: "పూకు",
    romanized: "pooku",
    language: "Telugu",
    languageCode: "te-IN",
    severity: "severe",
  },
  {
    word: "లవడ",
    romanized: "lavada",
    language: "Telugu",
    languageCode: "te-IN",
    severity: "severe",
  },
  {
    word: "బూతు",
    romanized: "boothu",
    language: "Telugu",
    languageCode: "te-IN",
    severity: "moderate",
  },
  {
    word: "గాడిద",
    romanized: "gaadida",
    language: "Telugu",
    languageCode: "te-IN",
    severity: "mild",
  },

  // Marathi
  {
    word: "गाढव",
    romanized: "gadhav",
    language: "Marathi",
    languageCode: "mr-IN",
    severity: "mild",
  },
  {
    word: "ढापू",
    romanized: "dhapu",
    language: "Marathi",
    languageCode: "mr-IN",
    severity: "mild",
  },
  {
    word: "भडवा",
    romanized: "bhadwa",
    language: "Marathi",
    languageCode: "mr-IN",
    severity: "severe",
  },
  {
    word: "चूतिया",
    romanized: "chutiya",
    language: "Marathi",
    languageCode: "mr-IN",
    severity: "severe",
  },
  {
    word: "झवाड़ी",
    romanized: "zhawadi",
    language: "Marathi",
    languageCode: "mr-IN",
    severity: "severe",
  },
  {
    word: "मादरचोद",
    romanized: "madarchod",
    language: "Marathi",
    languageCode: "mr-IN",
    severity: "severe",
  },
  {
    word: "रांड",
    romanized: "rand",
    language: "Marathi",
    languageCode: "mr-IN",
    severity: "severe",
  },
  {
    word: "बेशरम",
    romanized: "besharam",
    language: "Marathi",
    languageCode: "mr-IN",
    severity: "moderate",
  },

  // English
  {
    word: "stupid",
    romanized: "stupid",
    language: "English",
    languageCode: "en-US",
    severity: "mild",
  },
  {
    word: "idiot",
    romanized: "idiot",
    language: "English",
    languageCode: "en-US",
    severity: "mild",
  },
  {
    word: "dumb",
    romanized: "dumb",
    language: "English",
    languageCode: "en-US",
    severity: "mild",
  },
  {
    word: "moron",
    romanized: "moron",
    language: "English",
    languageCode: "en-US",
    severity: "moderate",
  },
  {
    word: "bastard",
    romanized: "bastard",
    language: "English",
    languageCode: "en-US",
    severity: "moderate",
  },
  {
    word: "damn",
    romanized: "damn",
    language: "English",
    languageCode: "en-US",
    severity: "mild",
  },
  {
    word: "ass",
    romanized: "ass",
    language: "English",
    languageCode: "en-US",
    severity: "moderate",
  },
  {
    word: "shit",
    romanized: "shit",
    language: "English",
    languageCode: "en-US",
    severity: "moderate",
  },
  {
    word: "fuck",
    romanized: "fuck",
    language: "English",
    languageCode: "en-US",
    severity: "severe",
  },
  {
    word: "bitch",
    romanized: "bitch",
    language: "English",
    languageCode: "en-US",
    severity: "severe",
  },
];
